### PR TITLE
Seamless Tutorial - One-stop shop to learn how to use the entire suite of Seamless models.

### PR DESCRIPTION
**Pull request by kauterry**
Adding our tutorial from NeurIPS 2023 - Seamless EXPO: https://fb.me/mt-neurips

### CODE REVIEW

**Review by uralik — COMMENTED** [review]
aligner part looks good to me!

**Review by elbayadm — COMMENTED** [review]
Do we still need `!pip install fairseq2==0.2.1.dev202311301403+cu118 --pre --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/nightly/pt2.1.1/cu118`?

**Comment by kauterry** [comment]
> Do we still need `!pip install fairseq2==0.2.1.dev202311301403+cu118 --pre --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/nightly/pt2.1.1/cu118`?

Thanks for the catch, we don't anymore. The stable version works with `pip install fairseq2`, let me change it.

**Review by elbayadm — APPROVED** [review]
Thanks for adding the tutorial notebook, lgtm!

**Pull request merged**
